config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'count', to: 'count#show', as: 'count_show'
  get 'help', to: 'help#index', as: 'help_index'
  get 'about', to: 'about#index', as: 'about_index'
  get 'stats', to: 'stats#index', as: 'stats_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_many :items

  validates :name, :content, presence: true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :event

  validates :name, presence: true
  validates :name, length: { minimum: 4 }

end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users

  validates :name, :code, presence: true
  validates :name, :code, length: { maximum: 16, minimum: 4 }
  validates :name, :code, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :role
  has_many :events

  validates :name, :email, :role_id, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true

end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/count_controller.rb
# frozen_string_literal: true

class CountController < ApplicationController
  @@collect = {}

  def show
    Rails.logger.info '#########################################'
    id = session[:session_id].to_sym
    if @@collect.key?(id)
      @@collect.store(id, @@collect[id] + 1)
    else
      @@collect.store(id, 1)
    end
    puts @@collect
    @val = @@collect
    Rails.logger.info '#########################################'
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index; end
end

app/controllers/help_controller.rb
# frozen_string_literal: true

class HelpController < ApplicationController
  def index; end
end

app/controllers/stats_controller.rb
# frozen_string_literal: true

class StatsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/about/index.html.slim
h2
  | About
br
p
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
  'ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
  'laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
  'voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
  'non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/count/show.html.slim
h2 Count
p
 = "You session #{session[:session_id]} - #{@val[session[:session_id].to_sym]}"

app/views/events/index.html.slim
h2
  | Events

app/views/help/index.html.slim
h2 
  | Help
br
p
  'Приложение GB ToDo пока не призвано решать практических задач.
  'Только в той лишь части, которая свзана с постиганием RoR

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GbTodo
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .header
      h1
        'GB ToDo Ruby app
    .nav
      ul
        li 
          = link_to_unless_current 'Домой', root_path
        li
          = link_to_unless_current 'Помощь', help_index_path
        li 
          = link_to_unless_current 'О нас', about_index_path
        li 
          = link_to_unless_current 'Статистика', stats_index_path
        li 
          = link_to_unless_current '#', count_show_path
    .content
      = yield
    
    .footer
      p
        | 2022 &copy;

app/views/stats/index.html.slim
h2 
  | Статистика
br
   table
    tr 
      th = 'Имя'
      th = 'Почта'
      th = 'Активен?'
      th = 'Всего задач'
      th = 'Активные задачи'
      th = 'Пункты'
      th = 'Активные пункты'
    - User.order(:name).each do |user|
      tr
       td = user.name
       td = user.email
       td = user.active
       td = Event.where(user_id: user.id).count
       td = Event.where(user_id: user.id, done: false).count
       td = Item.where(events_id: Event.where(user_id: user.id).ids).count
       td = Item.where(events_id: Event.where(user_id: user.id, done: false).ids).count